### ISSUE TITLE
Import of github.com/hashgraph/hedera-sdk-go/v2

### ISSUE THREAD

**Issue by hendrikebbers** [hiero-ledger/hiero-sdk-go#1156]
A lot of Go files have defined an import of `github.com/hashgraph/hedera-sdk-go/v2`. Example:

```
import (
	"fmt"
	"os"
	"github.com/hashgraph/hedera-sdk-go/v2"
)
```

I have no clue what `/v2` stands for but I assume we should take some action and get that string refactored to the new Hiero repository.

**Comment by cweagans** [comment]
Looks like this is in progress here: https://github.com/hiero-ledger/hiero-sdk-go/pull/1152

**Comment by 0xivanov** [comment]
fixed in https://github.com/hiero-ledger/hiero-sdk-go/pull/1152
