### ISSUE TITLE
release #1152 to new version

### ISSUE THREAD

**Issue by laggu** [hiero-ledger/hiero-sdk-go#1168]
installing package is not possible now.
It seems #1152 has merged but not yet released.

Would you plan for more fix??
I hope to know when the new version is released

**Comment by 0xivanov** [comment]
Hi @laggu , do you have problems installing only the latest version?

**Comment by laggu** [comment]
installing with `github.com/hiero-ledger/hiero-sdk-go` fail
but installing with `github.com/hashgraph/hedera-sdk-go` works

**Comment by 0xivanov** [comment]
Ok, we will release a new version tomorrow and hopefully the go modules can now find the new import uri.

**Comment by laggu** [comment]
working well now
